### PR TITLE
Update Degenics.md

### PR DESCRIPTION
**Pull request by Decentricity**
- Updated the infobox
- put "partners" in the correct section, and changed "type-org" to network

### CODE REVIEW

**Comment by Decentricity** [comment]
Hey @danwchan since you're online can you take a look at this? also, I wanted to add the logo but I don't have access to upload files on the Degenics folder -- can you help add [this file](https://drive.google.com/file/d/1P1NcReImWlI1wEtrtI91ugUfuOs6uBn6/view?usp=sharing) in?

**Comment by Decentricity** [comment]
@danwchan let me show you what i see when I try to add files into the Degenics entry:
image

**Comment by danwchan** [comment]
Ah yes I see you are trying to directly edit the sphere repository. You should upload and edit on your fork and then create a pull request from there.

**Comment by Decentricity** [comment]
@danwchan I see! I think i managed to do it correctly this time -- check out: [https://github.com/DIYbiosphere/sphere/pull/297](https://github.com/DIYbiosphere/sphere/pull/297)

**Pull request merged**
