### PR TITLE
Add new French Biohackerspace

### PR DESCRIPTION
**Pull request by XavCC**
Hi DIY BioSphere,

After 7 years, 
We finally decided to stop procrastinating.

So here we are, knocking on your repo door to add our humble boihackerspace to the ranks of its peers.

Let me know if something is wrong.

### CODE REVIEW

**Review by danwchan — CHANGES_REQUESTED** [review]
I'm not 100% sure how the the map works but you might want to also add a _geoloc on your page to ensure it comes up on the map. See [this example](https://raw.githubusercontent.com/DIYbiosphere/sphere/master/_labs/BiotechWithoutBorders/BiotechWithoutBorders.md)

Happy you got around to making your page! Please let others know we're still active and committed to letting the world know about local and global DIYbio initiatives.

**Comment by XavCC** [comment]
Thanks @danwchan 

I will add `_geoloc` and a new PR soon

**Comment by celleleven** [comment]
The _geoloc was added, and the entry was pushed live.  Can you verify the page?

**Comment by XavCC** [comment]
Hi @celleleven, checked `_geoloc` and it's perfect!

Also the page https://sphere.diybio.org/labs/kaouenn-noz/ is Ok but only one things:
- `Hosts` was filled whit `Self Hosting` https://github.com/DIYbiosphere/sphere/blob/master/_labs/Kaouenn-Noz/kaouenn-noz.md
- It doesn't appear on the web page, just a blank place https://sphere.diybio.org/labs/kaouenn-noz/

Any ideas?

**Comment by sjamesparsonsjr** [comment]
This section is for a parent organization, say a university or community lab.  How about I just remove the Host field?

**Comment by XavCC** [comment]
Well, if we/you provide information about hosting, like a parent organization, it could be also useful enable `self hosted` for people who wants to join the lab and also for research who wants to study labs.

a metaphor with websites/cloud could be:
+ Hosted at Amazon
+ Hosted at X University
+ Hosted in a community location
+ Self-hosted 

What do you think about this point of view?

**Comment by sjamesparsonsjr** [comment]
Sounds reasonable, what would you like your hosting to be?

**Comment by XavCC** [comment]
"Self-hosted" :wink:

**Pull request merged**
