### PR TITLE
Update Genspace.md

### PR DESCRIPTION
**Pull request by danwchan**
Please update Genspace description with the following text from our [website](https://www.genspace.org/)

Also please update our status to "active" and update our logo. 
https://images.squarespace-cdn.com/content/588b7cc315d5dbdea1425e5e/1570552144192-LKZBXTCCBNBD5IE3NRVM/a1.png?format=1500w&content-type=image%2Fpng

### CODE REVIEW

**Comment by danwchan** [comment]
@elizabethtuck are these changes just duplicates of the first one?

**Comment by elizabethtuck** [comment]
It wasn't clear to me how to make the requested updates, so I put it in
both places? whatever is needed to clean this up.

Thanks
-Beth

**Comment by sjamesparsonsjr** [comment]
I'm updating the logo.  What text do you want in the body?  

> Genspace is the world’s first community biology lab — a place where people of all backgrounds can learn, create, and grow with the life sciences. 

Since 2009, we have served the greater New York area by providing hands-on STEAM education programs for youth and adults, cultural and outreach events for the public, and a membership program to support New York’s community of creatives, researchers, and entrepreneurs. Our programs demystify scientific processes, provide a platform for innovation, and cultivate the next generation of life sciences leaders in emerging global technologies, such as biotechnology, neuroscience, epidemiology, genomics, and many more.

**Comment by elizabethtuck** [comment]
Hello!

Looks like the text has now been updated but our "status" still says
"unknown" - can you update that to active?

**Comment by danwchan** [comment]
There is no direct edit for status from what I can tell. From what I read going through old issues I think it might related to the date field.

**Review by 100ideas — APPROVED** [review]
looks fine

**Comment by 100ideas** [comment]
can't merge via github web... gonna see how it got out of date on command line...

**Comment by 100ideas** [comment]
@elizabethtuck ok resolved the commit issue the new copy should be live shortly.

sphere needs an overhaul... something to work on on the side this year... like user accounts that don't involve PRs to edit content maybe...

**Comment by jasonbobe** [comment]
thanks @100ideas for jumping in here!!!

**Comment by elizabethtuck** [comment]
Thank you all so much for your help! Really appreciate it!!
-Beth

**Pull request merged**
