### PR TITLE
Add katalab Vienna to the sphere :)

### PR DESCRIPTION
**Pull request by jscheithe**
Hi,

I'd like to add our soon-to-be-open biolab in Vienna :)

Thanks for your effort to create this, It's really cool!

Best, Jakob

### CODE REVIEW

**Comment by jasonbobe** [comment]
Awesome! Will review this weekend

**Comment by jasonbobe** [comment]
@jscheithe your stub post for Katalab is here:
[http://sphere.diybio.org/labs/katalab/](http://sphere.diybio.org/labs/katalab/)

**Comment by jscheithe** [comment]
Nice! Thanks, Jason.

When I start playing around with images etc, is there a way to preview changes without opening a new PR?

**Comment by jscheithe** [comment]
Hi Gabriela!
Thanks for the tutorial, I think I should be able to figure it out. If not, I'll write you.
Thank you :)

**Pull request merged**
