### PR TITLE
Create BentoLab.md

### PR DESCRIPTION
**Pull request by PhilippBoeing**

### CODE REVIEW

**Comment by jasonbobe** [comment]
thanks @PhilippBoeing 

merging....

**Comment by jasonbobe** [comment]
hi @PhilippBoeing sorry, i ran into a error via Travis CI. i'm working with @sabgaby and @100ideas to sort it out ASAP. Hope to see your post up soon.

**Comment by sabgaby** [comment]
@jasonbobe, @PhilippBoeing. The `Algolia_API_key` we were using stopped working for some reason. I tried out different ones, restarted the build until it passed.

**Comment by jasonbobe** [comment]
@PhilippBoeing your posting is live:

[http://sphere.diybio.org/startups/bentolab/](http://sphere.diybio.org/startups/bentolab/)

**Comment by PhilippBoeing** [comment]
thanks @jasonbobe

**Pull request merged**
