### PR TITLE
code cleanup & better responsive design

### PR DESCRIPTION
**Pull request by 100ideas**
### demo
https://diybiosphere-staging.netlify.com

### overview
1. added remote assets (css & js) to local assets
2. better use of jekyll-assets tags
3. semantic-ui grid cleanup on index.html landing page
4. responsive layout w/ semantic-ui on entry.html template
5. development log & deploy instructions in [docs/development.md](https://github.com/100ideas/sphere/blob/responsive-deploy/docs/development.md)

### details
- [x] **views using `entry` layout**
  - [x] social icons integrated into infobox
  - [x] metadata box floats below main content box, full-width in responsive mode
  - [x] refactor `info-box` partial
    - [x] create ___custom partial___ for better spacing instead of using table
  - [x] `tags` partial fine-tuned
- [ ] **landing**
  - [ ] logo shrinks to just square image, no text
  - [ ] global search box is front & center
  - [ ] use grid of 8 collection types as dynamic filter buttons
  - [ ] entries list component rendered below
- [ ] **entries list/filter view**
  - [ ] left-hand sidebar turns into button cloud
    - [x] in progress
    - [ ] turn into narrow stack of colored labels
    - [ ] https://semantic-ui.com/elements/label.html#colored-group
    - [ ] see `entries.html`
  - [ ] use as partial on landing page instead of dedicated page
  - [ ] search menu removed in favor of global search in top navbar
  - [ ] viewTable component in searchbox is unnecessary
  - [ ] pagination goes at bottom

### CODE REVIEW

**Comment by 100ideas** [comment]
I deleted the `.github` directory while I was cleaning things up because I didn't know what it was for, so this is causing trouble with TravisCI's build script.

Also, I disabled the jekyll algolia plugin via `_config.yml` for my staging deploy server, need to re-enable it (maybe?)

TravisCI error (missing directory): 
```
cp: cannot create regular file ‘.github/CONTRIBUTING.md’: No such file or directory
The command "cp docs/guides/contributing.md .github/CONTRIBUTING.md" failed and exited with 1 during .
```

@sabgaby could you provide some guidance on what all the folders are for in your master branch so I can better organize the code?  seems like there is a lot of redundancy and a fair amount of commented out modules (i.e. maps, instantsearch etc).

**Comment by 100ideas** [comment]
Secondly, we may want to switch to using netlify (hosting the staging server above) rather than TravisCI + github. It is a lot less complicated.

**Comment by sabgaby** [comment]
the `.github` folder is meant to clean up the root folder by holding the following files:

- ISSUE_TEMPLATE
- PULL_REQUEST_TEMPLATE
- CONTRIBUTING.md
- LICENSE.md
- CODE_OF_CONDUCT.md

If you are removing the `.github` folder, then the files should be moved to the root folder. 

The travis script copies the `.md` files for 'contributing' and the 'code-of-conduct' in the `docs`  and `about` foldesr to the `.github` folder so Github can show them to contributors. That's what the command that failing is trying to say:
```
cp docs/guides/contributing.md .github/CONTRIBUTING.md
cp about/code-of-conduct.md .github/CODE_OF_CONDUCT.md
```

This means that the files exist twice. I did this to avoid having to specify the permalink in the front matter. But yeah, maybe this is unnecessary.

To fix the broken build: you can remove the `cp` commands in the build script. If you are moving the build to Netlify then it shouldn't matter much since I guess you will be rebuilding the build script

I just sent you another invite link to administer the Algolia Index for the site's search function. You will need the API key to push to the index.

**Comment by 100ideas** [comment]
Ok, thanks @sabgaby. Could the `.github` folder be moved to `docs/github`?

Speaking of the project structure, do you have any thoughts on how we might more cleanly separate site files (templates, assets, code) from content? Everything is all jumbled together. I know this is *the jekyll way*, but the site is so big and there are so many different categories that its gotten a little confusing.

```
.
├── 404.html
├── DataReusePlan.txt
├── Gemfile
├── Gemfile.lock
├── README.md
├── _config.yml
├── _data
│   ├── database.csv
│   ├── database.json
│   └── images.yml
├── _events
│   ├── BioDesignChallenge
│   ├── BioFabbing
│   ├── BioHTP
│   ├── GlobalCommunityBioSummit
│   └── Igem
├── _groups
│   ├── BeInToBiohacking
│   ├── BioHackSyd
│   ├── BioHubIl
│   ├── BioTinkeringBerlin
│   ├── Biogarage
│   ├── BiohackersNYC
│   ├── BiohackingMexico
│   ├── CapCityBiohackers
│   ├── ChicagoBiohacking
│   ├── DIYNeurotech
│   ├── DIYbioAuckland
│   ├── DIYbioBuenosAires
│   ├── DIYbioChicago
│   ├── DIYbioGroningen
│   ├── DIYbioIreland
│   ├── DIYbioIsrael
│   ├── DIYbioMexico
│   ├── DIYbioPerth
│   ├── DIYbioSingapore
│   ├── GeneGarage
│   ├── Hackstronauts
│   ├── MNDIYbio
│   ├── ManilaBiopunk
│   └── TriDIYbio
├── _includes
│   ├── accordion.html
│   ├── cc-image.html
│   ├── contentMenu.html
│   ├── contentTab.html
│   ├── editOnGitHub.html
│   ├── footer.html
│   ├── githubComments.html
│   ├── githubCommentsEdit.html
│   ├── head.html
│   ├── header.html
│   ├── info-box.html
│   ├── keywords.html
│   ├── label
│   ├── map.html
│   ├── messages
│   ├── other
│   ├── pills.html
│   ├── promotions.html
│   ├── sidebar.html
│   ├── social-icons.html
│   ├── subtabs
│   ├── tabs
│   ├── tabs.html
│   └── video.html
├── _incubators
│   ├── BerkleyBiolabs
│   ├── BioTechAndBeyond
│   ├── BlueCity
│   ├── HarlemBiospace
│   ├── Hax
│   ├── IndieBio
│   └── RebelBio
├── _labs
│   ├── ArtScienceBlr
│   ├── BioArtLaboratories
│   ├── BioDidact
│   ├── BioFoundry
│   ├── BioMakersLabPeru
│   ├── BioNyfiken
│   ├── BioQuisitive
│   ├── BioTehna
│   ├── BioTown
│   ├── Biocurious
│   ├── BiologiGaragen
│   ├── BiologikLabs
│   ├── Bioscope
│   ├── BiotechWithoutBorders
│   ├── BosLab
│   ├── BricoBio
│   ├── BrmBiolab
│   ├── Bugss
│   ├── CapitalAreaBioSpace
│   ├── ChiTownBio
│   ├── CounterCultureLabs
│   ├── DIYBioBCN
│   ├── DIYBioTech
│   ├── DIYbioBelgium
│   ├── DIYbioToronto
│   ├── DenverBiolabs
│   ├── FLab
│   ├── GaroaOpenBiolab
│   ├── GaudiLabs
│   ├── Genspace
│   ├── Hackuarium
│   ├── HiveBio
│   ├── IndieLab
│   ├── LEprouvette
│   ├── LaJollaBiolab
│   ├── LaPaillase
│   ├── LaPaillaseSaone
│   ├── LeBiomeHackLab
│   ├── LifePatch
│   ├── LondonBiohackerspace
│   ├── MadLabBiolab
│   ├── OpenBioLabGraz
│   ├── OpenBioLabs
│   ├── OpenScienceNet
│   ├── OpenWetlab
│   ├── PechBlenda
│   ├── Reagent
│   ├── Symbiolab
│   ├── TheLAb
│   ├── TheWetlab
│   └── TrySciBiolab
├── _layouts
│   ├── default.html
│   ├── docs.html
│   ├── entries.html
│   ├── entry-example.html
│   ├── entry.html
│   ├── form.html
│   ├── image-info.html
│   ├── landing.html
│   ├── maps.html
│   ├── page.html
│   └── post.html
├── _networks
│   ├── BioChanges
│   ├── BioDesignFTRW
│   ├── DIYbio.org
│   ├── Hackteria
│   ├── NYCBio
│   └── SyntechBio
├── _plugins
│   ├── algolia_push.rb
│   ├── dataDoc.rb
│   ├── determine-collection.rb
│   ├── ext.rb
│   ├── include_absolute.rb
│   ├── jekyll-geocode.rb
│   ├── jekyll-sibling-images.rb
│   ├── references.rb
│   └── timestamp.rb
├── _projects
│   ├── BioDisplay
│   ├── DIYbiosphere
│   ├── KombuchaGenomics
│   ├── Metafluidics
│   ├── OYEP
│   ├── OpenGenX
│   ├── OpenInsulin
│   ├── OpenPcr
│   ├── RealVeganCheese
│   └── RoninGenetics
├── _references.md
├── _site
│   ├── 404.html
│   ├── about
│   ├── assets
│   ├── docs
│   ├── entries
│   ├── events
│   ├── favicon.ico
│   ├── feed.xml
│   ├── form
│   ├── groups
│   ├── incubators
│   ├── index.html
│   ├── labs
│   ├── maps
│   ├── networks
│   ├── projects
│   ├── robots.txt
│   ├── sitemap.xml
│   └── startups
├── _startups
│   ├── AminoLabs
│   ├── ChaiBio
│   ├── OpenTrons
│   ├── RotterZwam
│   └── TheODIN
├── assets
│   ├── css
│   ├── gifs
│   ├── img
│   ├── js
│   ├── semantic
│   ├── svg
│   └── videos
├── docs
│   ├── EntryTemplate.md
│   ├── about
│   ├── basics
│   ├── development.md
│   ├── drafts
│   ├── github
│   ├── guides
│   ├── introduction
│   ├── tutorials
│   └── welcome.md
├── favicon.ico
├── feed.xml
├── index.html
├── pages
│   ├── database.html
│   └── maps.html
└── script
    └── cibuild
```

**Comment by 100ideas** [comment]
`100ideas/sphere/master` has latest commits from `DIYbiosphere/sphere/master` and `100ideas/sphere/responsive-deploy`.

https://diybiosphere-staging.netlify.com now deploys from `100ideas/sphere/master`

closing this PR (since it uses `100ideas/sphere/responsive-deploy`) in favor of #196

```
git fetch origin -v; git fetch upstream -v; git merge upstream/master
git rebase responsive-deploy
git merge origin/master
git push
```

**Pull request closed without merging**
